import React, { useState } from 'react';
import { Sparkles, ArrowRight, Loader2 } from 'lucide-react';
import { generateConsultation } from '../services/geminiService';
import { ConsultationStatus } from '../types';
import Button from './Button';

const AIConsultant: React.FC = () => {
  const [businessType, setBusinessType] = useState('');
  const [goal, setGoal] = useState('');
  const [status, setStatus] = useState<ConsultationStatus>(ConsultationStatus.IDLE);
  const [result, setResult] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!businessType || !goal) return;

    setStatus(ConsultationStatus.LOADING);
    try {
      const advice = await generateConsultation(businessType, goal);
      setResult(advice);
      setStatus(ConsultationStatus.SUCCESS);
    } catch (error) {
      setStatus(ConsultationStatus.ERROR);
    }
  };

  return (
    <div className="bg-gradient-to-br from-eco-900 to-eco-950 text-white rounded-3xl overflow-hidden shadow-2xl mx-4 lg:mx-auto max-w-6xl relative">
      <div className="absolute top-0 right-0 w-96 h-96 bg-eco-500/10 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2" />
      
      <div className="grid lg:grid-cols-2 gap-12 p-8 md:p-12 lg:p-16 relative z-10">
        <div className="flex flex-col justify-center">
          <div className="inline-flex items-center space-x-2 text-eco-300 mb-6">
            <Sparkles className="w-5 h-5" />
            <span className="font-medium tracking-wide text-sm uppercase">AI Strategy Preview</span>
          </div>
          <h3 className="font-serif text-3xl md:text-4xl mb-6 leading-tight">
            See how sustainable tech transforms your business.
          </h3>
          <p className="text-eco-100/80 text-lg mb-8 leading-relaxed">
            Not ready to commit? Get a free, instant strategic insight generated by our custom AI model trained on sustainable web practices.
          </p>
          
          {result && (
             <div className="bg-white/10 backdrop-blur-md rounded-xl p-6 border border-white/20 animate-fade-in">
               <h4 className="text-eco-300 font-semibold mb-2 text-sm uppercase tracking-wider">Strategic Insight</h4>
               <p className="text-white leading-relaxed">{result}</p>
               <button 
                 onClick={() => { setResult(null); setStatus(ConsultationStatus.IDLE); setBusinessType(''); setGoal(''); }}
                 className="mt-4 text-sm text-eco-300 hover:text-white underline decoration-eco-500/50 hover:decoration-white transition-all"
               >
                 Try another scenario
               </button>
             </div>
          )}
        </div>

        <div className={`transition-all duration-500 ${result ? 'opacity-50 pointer-events-none' : 'opacity-100'}`}>
          <form onSubmit={handleSubmit} className="bg-white text-slate-900 p-8 rounded-2xl shadow-xl">
            <h4 className="font-serif text-2xl mb-6">Describe your vision</h4>
            
            <div className="space-y-6">
              <div>
                <label className="block text-sm font-semibold text-slate-600 mb-2">Business Type</label>
                <input
                  type="text"
                  placeholder="e.g. Organic Coffee Shop, SaaS Platform, Legal Firm"
                  value={businessType}
                  onChange={(e) => setBusinessType(e.target.value)}
                  className="w-full px-4 py-3 rounded-lg border border-slate-200 focus:border-eco-500 focus:ring-2 focus:ring-eco-200 transition-all outline-none"
                  required
                />
              </div>
              
              <div>
                <label className="block text-sm font-semibold text-slate-600 mb-2">Primary Goal</label>
                <select
                  value={goal}
                  onChange={(e) => setGoal(e.target.value)}
                  className="w-full px-4 py-3 rounded-lg border border-slate-200 focus:border-eco-500 focus:ring-2 focus:ring-eco-200 transition-all outline-none bg-white"
                  required
                >
                  <option value="" disabled>Select a goal...</option>
                  <option value="Increase Conversions">Increase Conversions</option>
                  <option value="Improve Brand Perception">Improve Brand Perception</option>
                  <option value="Reduce Carbon Footprint">Reduce Digital Carbon Footprint</option>
                  <option value="Expand Globally">Expand to Global Markets</option>
                </select>
              </div>

              <Button 
                variant="primary" 
                className="w-full justify-between group"
                disabled={status === ConsultationStatus.LOADING}
              >
                {status === ConsultationStatus.LOADING ? (
                  <>
                    <span>Analyzing...</span>
                    <Loader2 className="w-5 h-5 animate-spin" />
                  </>
                ) : (
                  <>
                    <span>Generate Strategy</span>
                    <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                  </>
                )}
              </Button>
            </div>
            <p className="mt-4 text-xs text-center text-slate-400">
              Powered by Google Gemini 2.5 Flash. Results are for demonstration.
            </p>
          </form>
        </div>
      </div>
    </div>
  );
};

export default AIConsultant;